#![cfg_attr(not(test), deny(clippy::unwrap_used, clippy::expect_used))]

mod accname;
pub mod action;
pub mod action_request;
pub mod action_result;
pub mod action_step;
pub mod action_step_outcome;
pub(crate) mod actionability;
mod adapter;
mod adapter_error;
mod adapter_session;
mod app_error;
mod app_info;
mod app_inventory;
mod app_lookup;
pub mod capability;
pub mod cdp_endpoint;
mod clipboard_content;
mod clipboard_format;
pub mod commands;
mod containment_predicate;
pub mod context;
pub mod cursor_overlay;
mod deadline;
mod delivery_disposition;
mod delivery_semantics;
mod direction;
mod dismiss_all_notifications_request;
mod dismiss_notification_request;
pub mod display_info;
mod drag_params;
mod element_identifier;
pub mod element_state;
mod error_code;
mod event_kind;
mod file_lock;
mod headed_focus;
mod headed_requirement;
pub mod hints;
pub mod hit_test;
mod identifier_kind;
mod identity_predicate;
mod image_buffer;
mod image_format;
mod interaction_lease;
pub mod interaction_policy;
mod key_combo;
pub mod launch_options;
pub mod launch_result;
pub mod live_element;
mod live_identity;
mod live_locator;
pub(crate) mod locator;
mod modifier;
mod mouse_button;
mod mouse_click_count;
mod mouse_event;
mod mouse_event_kind;
mod name_evidence;
mod name_slot_status;
pub mod native_handle;
mod node;
mod node_descriptor;
mod node_identity;
mod node_match_context;
mod node_presentation;
mod notification_action_request;
mod notification_filter;
mod notification_identity;
mod notification_info;
pub mod output;
pub mod permission_report;
pub mod permission_state;
mod point;
mod post_action;
mod private_file;
mod private_file_ops;
mod private_file_parent;
mod process_id;
mod process_identity;
mod process_lease_guard;
pub mod process_state;
mod recovery_hint;
mod rect;
pub mod ref_action;
mod ref_action_actionability;
mod ref_action_context;
mod ref_action_poll;
mod ref_action_poll_state;
mod ref_action_single;
mod ref_action_wait;
mod ref_action_wait_context;
mod ref_action_wait_evidence;
mod ref_action_wait_support;
pub mod ref_alloc;
mod ref_alloc_config;
mod ref_alloc_options;
mod ref_alloc_scope;
mod ref_alloc_source;
mod ref_allocation;
mod ref_capabilities;
mod ref_entry;
mod ref_entry_identity;
mod ref_geometry;
pub mod ref_identity;
mod ref_identity_match;
mod ref_process;
mod ref_resolve_deadline;
mod ref_scope;
mod ref_source;
mod ref_token;
pub mod refs;
mod refs_lock;
pub mod refs_store;
#[cfg(test)]
mod refs_test_support;
mod refs_validate;
mod renderer_accessibility;
mod renderer_kind;
mod resolve_attempt_outcome;
pub mod resolve_errors;
mod retry_disposition;
mod retryability;
mod role;
pub mod role_text;
pub mod roles;
pub mod screenshot_target;
pub(crate) mod search_text;
pub mod session;
mod session_affinity;
mod signal_baseline;
mod signal_completeness;
mod signal_filter;
pub(crate) mod signals;
pub mod snapshot;
pub mod snapshot_ref;
pub mod snapshot_surface;
pub mod state;
mod state_predicate;
pub(crate) mod state_root;
pub mod step_mechanism;
mod surface_info;
mod surface_signal;
pub(crate) mod trace;
mod trace_artifact_budget;
pub(crate) mod trace_artifacts;
mod trace_file;
pub mod trace_read;
pub mod trace_sanitize;
mod trace_state;
pub mod tree_options;
mod ui_event;
mod value_matches;
mod wait_budget;
pub mod window_filter;
mod window_focus;
mod window_info;
mod window_lookup;
mod window_op;
mod window_state;

pub use accname::{compute_description, compute_name, resolve_description, resolve_name};
pub use action::Action;
pub use action_request::ActionRequest;
pub use action_result::ActionResult;
pub use action_step::ActionStep;
pub use action_step_outcome::ActionStepOutcome;
pub use adapter::PlatformAdapter;
pub use adapter::actions::ActionOps;
pub use adapter::input::InputOps;
pub use adapter::observation::ObservationOps;
pub use adapter::system::SystemOps;
pub use adapter_error::AdapterError;
pub use adapter_session::AdapterSession;
pub use app_error::AppError;
pub use app_info::{AppInfo, AppPresentation, app_name_matches};
pub use app_inventory::AppInventory;
pub use clipboard_content::ClipboardContent;
pub use clipboard_format::ClipboardFormat;
pub use containment_predicate::ContainmentPredicate;
pub use context::{CommandContext, WaitSelector};
pub use cursor_overlay::{
    CURSOR_ARRIVAL_TIMEOUT_MS, CURSOR_HIGHLIGHT_HOLD_MS, CURSOR_IDLE_REST_MS,
    CURSOR_LABEL_REVEAL_MS, CURSOR_MOTION_BUDGET_MS, CURSOR_OVERLAY_GREETING, CURSOR_REST_FADE_MS,
    CursorAim, CursorImage, CursorImages, CursorMotion, CursorMotionProfile, CursorOverlayConfig,
    CursorOverlayControl, CursorOverlayInstruction, CursorOverlayStyle, CursorPhase, CursorPose,
    CursorShape, MAX_CURSOR_IMAGE_BYTES, MAX_CURSOR_IMAGE_PATH_BYTES, MAX_CURSOR_IMAGE_PIXELS,
    MAX_CURSOR_LABEL_BYTES, MAX_CURSOR_LABEL_WORDS, place_label,
};
pub use deadline::{DEFAULT_OPERATION_TIMEOUT_MS, Deadline};
pub use delivery_disposition::DeliveryDisposition;
pub use delivery_semantics::DeliverySemantics;
pub use direction::Direction;
pub use dismiss_all_notifications_request::DismissAllNotificationsRequest;
pub use dismiss_notification_request::DismissNotificationRequest;
pub use display_info::DisplayInfo;
pub use drag_params::{DragParams, MAX_DRAG_DROP_DELAY_MS, MAX_DRAG_DURATION_MS, MAX_DRAG_STEPS};
pub use element_identifier::ElementIdentifier;
pub use element_state::ElementState;
pub use error_code::ErrorCode;
pub use event_kind::EventKind;
pub use file_lock::FileLock;
pub use headed_requirement::HeadedRequirement;
pub use hit_test::HitTestResult;
pub use identifier_kind::IdentifierKind;
pub use identity_predicate::IdentityPredicate;
pub use image_buffer::{ImageBuffer, MAX_PNG_INPUT_BYTES, parse_png_dimensions};
pub use image_format::ImageFormat;
pub use interaction_lease::InteractionLease;
#[cfg(unix)]
pub use interaction_lease::{
    INTERACTION_LEASE_FD_ENV, acquire_unix_interaction_lease,
    adopt_inherited_unix_interaction_lease,
};
pub use interaction_policy::InteractionPolicy;
pub use key_combo::KeyCombo;
pub use live_element::LiveElement;
pub use live_identity::LiveIdentity;
pub use live_locator::{
    EvidenceRequirements, IdentifierEvidence, LocatorCardinality, LocatorEvidence, LocatorField,
    LocatorIdentifierStats, LocatorLimitStats, LocatorMaterialization, LocatorReadCounts,
    LocatorReadHealth, LocatorReadStats, LocatorRefEvidence, LocatorResolution,
    LocatorResolveRequest, LocatorSelection, LocatorSemanticReadStats, LocatorStats,
    LocatorTraversalStats, ObservationBudget, ObservationMode, ObservationRequest, ObservationRoot,
    ObservationSource, ObservedSubtree, ObservedTree, classify_query_result, evaluate_locator_tree,
    require_unique, resolve_query,
};
pub use locator::{
    LocatorQuery, accessibility_node_matches, node_context, node_matches, role_matches,
};
pub use modifier::Modifier;
pub use mouse_button::MouseButton;
pub use mouse_click_count::{MAX_MOUSE_CLICK_COUNT, validate_mouse_click_count};
pub use mouse_event::MouseEvent;
pub use mouse_event_kind::MouseEventKind;
pub use name_evidence::NameEvidence;
pub use name_slot_status::{NameSlotStatus, SlotStatus};
pub use native_handle::NativeHandle;
pub use node::AccessibilityNode;
pub use node_descriptor::NodeDescriptor;
pub use node_identity::NodeIdentity;
pub use node_match_context::NodeMatchContext;
pub use node_presentation::NodePresentation;
pub use notification_action_request::NotificationActionRequest;
pub use notification_filter::NotificationFilter;
pub use notification_identity::NotificationIdentity;
pub use notification_info::NotificationInfo;
pub use output::{ErrorPayload, Response};
pub use permission_report::PermissionReport;
pub use permission_state::PermissionState;
pub use point::Point;
pub use post_action::execute_verified_action;
pub use private_file_ops::{
    PrivateFileOps, bounded_read, install_private_file_ops, temporary_file_name,
};
pub use process_id::ProcessId;
pub use process_identity::ProcessIdentity;
pub use process_lease_guard::ProcessLeaseGuard;
pub use recovery_hint::RecoveryHint;
pub use rect::Rect;
pub use ref_capabilities::RefCapabilities;
pub use ref_entry::RefEntry;
pub use ref_entry_identity::RefEntryIdentity;
pub use ref_geometry::RefGeometry;
pub use ref_identity_match::IdentityMatch;
pub use ref_process::RefProcess;
pub use ref_scope::RefScope;
pub use ref_source::RefSource;
pub use refs::RefMap;
pub use refs_store::RefStore;
pub use renderer_kind::RendererKind;
pub use retry_disposition::RetryDisposition;
pub use role::Role;
pub use screenshot_target::ScreenshotTarget;
pub use session_affinity::SessionAffinity;
pub use signal_baseline::SignalBaseline;
pub use signal_completeness::SignalCompleteness;
pub use signal_filter::SignalFilter;
pub use signals::diff_signals;
pub use snapshot_surface::SnapshotSurface;
pub use state_predicate::StatePredicate;
pub use state_root::validate_state_root_env;
pub use step_mechanism::StepMechanism;
pub use surface_info::SurfaceInfo;
pub use surface_signal::SurfaceSignal;
pub use trace_sanitize::sanitize_trace_value;
pub use tree_options::TreeOptions;
pub use ui_event::UiEvent;
pub use value_matches::value_matches;
pub use wait_budget::{MAX_WAIT_TIMEOUT_MS, wait_timeout_duration};
pub use window_filter::WindowFilter;
pub use window_info::WindowInfo;
pub use window_op::WindowOp;
pub use window_state::WindowState;
